version: "3"
services:
  php:
    image: wulaphp/php:7.4-dev
    ports:
      - 8808:80/tcp
    volumes:
      - "./:/var/www/html/"
      - "./docker/etc/nginx/nginx.conf:/usr/local/etc/nginx/nginx.conf:ro"
  mysql:
    image: mysql:5.7.31
    volumes:
      - "./storage/mysql:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  redis:
    image: redis:6.0.7-buster
    sysctls:
      net.core.somaxconn: 1024