language: php

if: tag IS present

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql
  - postgresql
  - memcached
  - redis-server
  - docker

addons:
  apt:
    packages:
      - parallel
      - gearman-job-server
      - libgearman-dev

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"

matrix:
  fast_finish: true

before_install:
  # disable xdebug if available
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # disable default memory limit
  - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo memory_limit = -1 >> $INI
  - mkdir -p tests/storage/
  - mkdir tests/storage/tmp
  - mkdir tests/storage/logs
  - docker pull wendal/ssdb
  - docker run --rm -d -p 8888:8888 wendal/ssdb
  - gearmand -d -l tests/storage/logs/gm.log

install:
  - wget https://github.com/wcgallego/pecl-gearman/archive/gearman-2.0.6.tar.gz
  - tar -zxf gearman-2.0.6.tar.gz
  - pushd pecl-gearman-gearman-2.0.6/ && phpize && ./configure && make && make install && popd
  - echo "extension = gearman.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # flags to pass to install
  - flags="--prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  # install dependencies using system provided composer binary
  - composer install $flags

before_script:
  - php tests/artisan service start
  - php -S 127.0.0.1:9090 -t tests/www/ tests/www/index.php > /dev/null 2>&1 &
  - netstat -naltp | grep 4730

script:
  - ls -d tests/Tests/**/* | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c tests/phpunit.xml.dist --colors=always {} || (echo -e "\e[41mFAILED\e[0m {}" && exit 1);'
